Featue branch
keddo/Enumerable pull request #2
Opened 2020-06-23 13:03 UTC by paulzay

### What does this PR do?
Rebuild ruby enumerables from scratch. 
### Description of tasks to be completed? 
<div class="lesson-content__panel" markdown="1">

1. Create a script file to house your methods and run it in IRB to test them later.
2. Add your new methods onto the existing Enumerable module.  Ruby makes this easy for you because any class or module can be added to without trouble ... just do something like:

~~~ruby
  module Enumerable
    def my_each
      # your code here
    end
  end
~~~

3. Create `#my_each`, a method that is identical to `#each` but (obviously) does not use `#each`.  You'll need to remember the `yield` statement.  Make sure it returns the same thing as `#each` as well.
4. Create `#my_each_with_index` in the same way.
5. Create `#my_select` in the same way, though you may use `#my_each` in your definition (but not `#each`).
6. Create `#my_all?` (continue as above)
7. Create `#my_any?`
8. Create `#my_none?`
9. Create `#my_count`
10. Create `#my_map`
11. Create `#my_inject`
12. Test your `#my_inject` by creating a method called `#multiply_els` which multiplies all the elements of the array together by using `#my_inject`, e.g. `multiply_els([2,4,5]) #=> 40`
13. Modify your `#my_map` method to take a proc instead.
14. Modify your `#my_map` method to take either a proc or a block. It won't be necessary to apply both a proc and a block in the same `#my_map` call since you could get the same effect by chaining together one `#my_map` call with the block and one with the proc. This approach is also clearer, since the user doesn't have to remember whether the proc or block will be run first. So if both a proc and a block are given, only execute the proc.

2020-06-23 19:21 UTC, mcrd25 requested changes
# Changes Required 🔍 

Hey Team! 👋 

Great attempt! however, you are missing some minor implementation details.
Consider my review comments and address them! Hope they can help 🤞 

Don't forget to check out https://ruby-doc.org/core-2.6.5/Enumerable.html if you need clearer idea of how any method works.

Also, tip: Consider ranges for each method you implement! 


***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-06-23 19:21 UTC, mcrd25 commented on enumerables.rb
> +  def my_select
YOu should also have this method work when it's a range. 
Currently, it returns nil and not an array when range passed because you have not considered ranges in this method.

2020-06-23 19:21 UTC, mcrd25 commented on enumerables.rb
> +  def my_none?(obj = nil)
Similarly to how `my_all?` handles Class and Regexp, you `my_none` needs to be able to handle this type of arg.

2020-06-23 19:21 UTC, mcrd25 commented on enumerables.rb
> +  def my_any?(*args)
Similarly to how `my_all?` handles Class and Regexp, you `my_any?` needs to be able to handle this type of arg.

2020-06-23 19:21 UTC, mcrd25 commented on enumerables.rb
> +  # def my_inject(i = 0)
Remove commented-out code.
t’s better to delete commented code. If you need to review a previous version of your code, use git history.
See this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png)
Please remove! 🙏

2020-06-23 19:21 UTC, mcrd25 commented on enumerables.rb
> +  def my_map(&proc)
Don't forget that you ought to return Enumerator when no block given. 

Please address

2020-06-23 19:21 UTC, mcrd25 commented on enumerables.rb
> +  def my_count(num = 0)
[OPTIONAL]
better to set it to nil rather than 0.

2020-06-23 19:21 UTC, mcrd25 commented on enumerables.rb
> +    sum = max if !block_given? && num.zero?
You should return length according to the definition of #my_count in this documentation: https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png
when no block or arg given.

2020-06-23 19:21 UTC, mcrd25 commented on enumerables.rb
> +  def my_count(num = 0)
Currently, your my_count gives some wrong answers due to some of the comments I gave. Consider even my OPTIONAL COMMENTS.

2020-06-23 19:21 UTC, mcrd25 commented on enumerables.rb
> +  def my_each
HINT 💡 
If you address range class here you would automatically address in other methods. Please do this

2020-06-23 19:21 UTC, mcrd25 commented on enumerables.rb
> +  def my_inject(*args)
You `my_inject` has the most failing tests. Consider reviewing it here: https://ruby-doc.org/core-2.6.5/Enumerable.html#method-i-inject

2020-06-23 19:21 UTC, mcrd25 commented on enumerables.rb
> +  def my_inject(*args)
Consider:
- When a symbol is specified without an initial value
- when a symbol is specified with the initial value.

Basically consider when argument  1 is a symbol and of course if there is a second argument the second argument is a symbol

2020-06-24 10:12 UTC, lekegitrepo commented
#### Good job :muscle:
##### This project is approved :100: :1st_place_medal:

#### _Reviewed by Temitayo Adeleke_.

2020-06-24 10:13 UTC, lekegitrepo approved these changes
#### Status: Approved.

2020-06-24 10:17 UTC, merged